describe("erochest.ui", function ()
  describe("get_git_branch", function ()
    it("finds the current branch name", function()
      -- local git_process = assert(io.popen("git branch --show-current", "r"))
      local branch_name = require("erochest.ui").get_git_branch()
      assert.equal("neovim-lua", branch_name)
    end)
  end)
end)
